name: Release Translator

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      '6.8.2'
        host:         'windows'
        target:       'desktop'
        arch:         'win64_msvc2022_64'
        modules:      'qtcharts qtnetworkauth qtmultimedia'
        install-deps: true
        dir:          'C:/Qt'
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Configure
      shell: cmd
      run: |
        set PATH=C:\Qt\6.8.2\msvc2022_64\bin;%PATH%
        qmake
        
    - name: Build
      shell: cmd
      run: |
        nmake
        
    - name: Copy DLLs
      shell: cmd
      run: |
        windeployqt --release --qmldir . bin\release\Translator.exe

    - name: Cleanup Release Directory
      shell: powershell
      run: |
        Get-ChildItem -Path bin/release -Recurse -Filter *.obj | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path bin/release -Recurse -Filter *.cpp | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path bin/release -Recurse -Filter *.h | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path bin/release -Recurse -Filter *.qrc | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path bin/release -Recurse -Filter *.qml | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path bin/release -Recurse -Filter *.ui | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path bin/release -Recurse -Filter *.qm | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path bin/release -Recurse -Filter *.qmldir | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path bin/release -Recurse -Filter *.qmltypes | Remove-Item -Force -ErrorAction SilentlyContinue

    - name: Compress Release
      shell: cmd
      run: |
        powershell Compress-Archive -Path bin\release\* -DestinationPath release.zip
        
    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: Translator
        path: release.zip
        retention-days: 30 


    - name: Debug GITHUB_TOKEN
      shell: powershell
      run: |
        if ($env:GITHUB_TOKEN) {
          Write-Host "GITHUB_TOKEN is defined."
        } else {
          Write-Host "GITHUB_TOKEN is NOT defined."
        }

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
